version: "3.3"

services:

  db:
      image: postgres:13.9-alpine3.17
      container_name: los-db
      environment:
        - DATABASE_HOST=los-db
        - POSTGRES_USER=uatpostgres
        - POSTGRES_PASSWORD=12345
        - POSTGRES_DB=los
      volumes:
        - postgres-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - appnet

  api:
    container_name: los-service
    build: .
    ports:
      - "9090:9090"
    networks: ['appnet']
    environment:
      - DSN="host=los-db user=uatpostgres password=12345 dbname=los port=5432 sslmode=disable"
    env_file: .env.vm
    depends_on:
      - db

  

volumes:
  postgres-data:

networks:
  appnet:
    driver: bridge