consumes:
    - application/json
info:
    description: A LOS API service for Open Lending.
    title: Lending LOS Service
    version: 1.0.0
paths: {}
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
